### ISSUE TITLE
ocprometheus not able to parse complex path

### ISSUE THREAD

**Issue by topine** [aristanetworks/goarista#51]
Hello,

I`m trying to collect LLDP data using the telemetry paths ( that I found in CVP ) :

/Sysdb/l2discovery/lldp/status/local/1/portStatus/Ethernet1/1/remoteSystem/2 :
sysName : {   "value": "NeighborHostname" }

Exporter config :

```
Metrics:
   - name: lldpNeighborInfo
     path: /Sysdb/l2discovery/lldp/status/local/(?P<localIndex>.+)/portStatus/(?P<intf>.+)/remoteSystem/(?P<remoteSystemIndex>.+)/sysName/value
     help: LLDP metric info
     valuelabel: neighborName
     defaultvalue: 1

```

The metric is not mapped and no error logs are found.

I`m trying other paths to debug and when I try the config below :

```
       - name: lldpPortStatus
          path: /Sysdb/l2discovery/lldp/status/local/1/portStatus/(?P<intf>.+)/(?P<type>.+)
          help: Test with PortStatus
          valuelabel: textValue
```

Seems the path changes for the remotesystem, adding "_counts" after the interface :

`lldpPortStatus{intf="Ethernet10\/3/_counts",job="poc-arista",textValue="textValue",type="remoteSystem"}
`
EOS : 4.22.4M

Could you please verify?

Thank you,
Anderson Topine
