### ISSUE TITLE
Add cloudEOS DPS examples

### ISSUE THREAD

**Issue by noredistribution** [aristanetworks/goarista#59]
e.g.:
```
metrics:
        - name: dpslatency
          path: /Smash/its/sessStatus/itsSessCharacData/(?P<dpskey>.*)/latency
          help: DPS latency
        - name: dpsthroughput
          path: /Smash/its/sessStatus/itsSessCharacData/(?P<dpskey>.*)/throughput
          help: DPS throughput
        - name: dpsloss
          path: /Smash/its/sessStatus/itsSessCharacData/(?P<dpskey>.*)/loss
          help: DPS loss
        - name: dpsjitter
          path: /Smash/its/sessStatus/itsSessCharacData/(?P<dpskey>.*)/jitter
          help: DPS jitter
```
