### ISSUE TITLE
ocprometheus fails with duplicated metrics with EOS 4.27

### ISSUE THREAD

**Issue by freedge** [aristanetworks/goarista#67]
Using latest goarista from master branch, EOS 4.27.4M, and a configuration like this:
```
metrics:

        - name: ocprometheus_bgp_peer_as_number  #No unit
          path: /Sysdb/routing/bgp/export/vrfBgpPeerInfoStatusEntryTable/(?P<vrf>.+)/bgpPeerInfoStatusEntry/(?P<name>.+)/bgpPeerAs
          help: BGP Peer  AS Number
```

ocprometheus fails with errors like this:

```
* collected metric "ocprometheus_bgp_peer_as_number" { label:<name:"name" value:"192.168.247.17" > label:<name:"vrf" value:"default" > gauge:<value:0 > } was collected before with the same name and label values
```

This used to work so far with EOS <= 4.26.6M :

```
ocprometheus_bgp_peer_as_number{name="10.64.226.33/bgpPeerSessionStatus",vrf="default"} 1234
ocprometheus_bgp_peer_as_number{name="10.64.226.35/bgpPeerSessionStatus",vrf="default"} 1234
ocprometheus_bgp_peer_as_number{name="192.168.247.19/bgpPeerSessionStatus",vrf="default"} 64850
ocprometheus_bgp_peer_as_number{name="192.168.248.19/bgpPeerSessionStatus",vrf="default"} 64850
```

It looks like the name "(?P<name>.+)" used to match "10.64.226.33/bgpPeerSessionStatus", but now it only constructs a label with the first part before the first "/"
